INSERT INTO categories (name, slug, description) VALUES
('Linux', 'linux', 'Linux administration and commands'),
('Docker', 'docker', 'Containerization with Docker'),
('Kubernetes', 'kubernetes', 'Container orchestration'),
('AWS', 'aws', 'Amazon Web Services'),
('Terraform', 'terraform', 'Infrastructure as Code'),
('Jenkins', 'jenkins', 'CI/CD automation server'),
('Git', 'git', 'Version control system'),
('GitHub', 'github', 'Git hosting and collaboration'),
('Shell Scripting', 'shell-scripting', 'Bash and shell scripting'),
('Networking', 'networking', 'Computer networks basics'),
('Ansible', 'ansible', 'Configuration management'),
('Prometheus', 'prometheus', 'Monitoring and alerting'),
('Grafana', 'grafana', 'Data visualization'),
('SonarQube', 'sonarqube', 'Code quality'),
('Monitoring', 'monitoring', 'General monitoring concepts'),
('CI/CD', 'ci-cd', 'Continuous Integration/Delivery'),
('Nginx', 'nginx', 'Web server/reverse proxy'),
('Apache', 'apache', 'Web server'),
('DevSecOps', 'devsecops', 'Security in DevOps'),
('GitOps', 'gitops', 'Git-based operations'),
('Python for DevOps', 'python-for-devops', 'Python scripting for DevOps'),
('Cloud Fundamentals', 'cloud-fundamentals', 'Cloud computing basics')
ON CONFLICT (slug) DO NOTHING;